//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NDBPRules {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NDBPRules.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The characters &quot;{0}&quot; are not allowed in the HelpText property.
        /// </summary>
        public static string InvalidCharacters {
            get {
                return ResourceManager.GetString("InvalidCharacters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifies that invalid characters are not used.
        /// </summary>
        public static string InvalidCharactersDescription {
            get {
                return ResourceManager.GetString("InvalidCharactersDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The word &apos;{0}&apos; is not allowed in any method names..
        /// </summary>
        public static string NotAllowedWord {
            get {
                return ResourceManager.GetString("NotAllowedWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifies that specific words don&apos;t appear in code artifacts..
        /// </summary>
        public static string NotAllowedWordDescription {
            get {
                return ResourceManager.GetString("NotAllowedWordDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration key should be specified.
        /// </summary>
        public static string TableConfigurationKeyMissing {
            get {
                return ResourceManager.GetString("TableConfigurationKeyMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration key should be specified.
        /// </summary>
        public static string TableConfigurationKeyMissingDescription {
            get {
                return ResourceManager.GetString("TableConfigurationKeyMissingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table group should be specified.
        /// </summary>
        public static string TableGroupMissing {
            get {
                return ResourceManager.GetString("TableGroupMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table group should be specified.
        /// </summary>
        public static string TableGroupMissingDescription {
            get {
                return ResourceManager.GetString("TableGroupMissingDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration key should be specified.
        /// </summary>
        public static string ViewConfigurationKeyMissing {
            get {
                return ResourceManager.GetString("ViewConfigurationKeyMissing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration key should be specified.
        /// </summary>
        public static string ViewConfigurationKeyMissingDescription {
            get {
                return ResourceManager.GetString("ViewConfigurationKeyMissingDescription", resourceCulture);
            }
        }
    }
}
